bgremove/urls.py
from django.urls import path

from .views import ResultView, UploadView

app_name = "bgremove"

urlpatterns = [
    path("", UploadView.as_view(), name="home"),
    path("result/<slug:slug>/", ResultView.as_view(), name="result"),
]

config/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("bgremove.urls")),
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bgremove/models.py
from datetime import datetime
from uuid import uuid4

from django.db import models
from django.urls import reverse


def get_upload_path(instance, filename):
    """Return timestamp filename for user uploaded files."""

    ext = filename.split(".")[-1]
    time_stamp = datetime.today().strftime("%Y%m%d_%H%M%S")
    folder = datetime.today().strftime("%Y/%m")
    image_path = f"{folder}/{time_stamp}.{ext}"
    return image_path


class UserActivity(models.Model):
    """
    A class representing user activity

    Uploading image to remove its background and downloading.
    """

    image = models.ImageField(upload_to=get_upload_path)
    result = models.ImageField(upload_to=get_upload_path)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(default=uuid4)

    class Meta:
        verbose_name = "User Activity"
        verbose_name_plural = "User Activities"

    def __str__(self) -> str:
        return str(self.slug)

    def get_absolute_url(self):
        return reverse("bgremove:result", args=(self.slug,))

bgremove/views.py
from django.views.generic import CreateView, DetailView

from .models import UserActivity


class UploadView(CreateView):
    model = UserActivity
    fields = ["image"]
    template_name = "index.html"


class ResultView(DetailView):
    model = UserActivity
    template_name = "result.html"
    context_object_name = "user_activity"

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} Background Remover {% endblock %}</title>
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  {% block page_css %} {% endblock %}
</head>

<body>

  <div class="container-fuild vh-100 d-flex flex-column">

    <nav class="navbar navbar-expand-md bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'bgremove:home' %}">Background Remover</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'bgremove:home' %}">Upload</a>
            </li>
            <li class="nav-item align-self-center d-none d-lg-block">
              <span class="mx-2">|</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/balewgize/background-remover" target="_blank"><i
                  class="fa-brands fa-github me-2"></i>Github</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="row bg-light">
      <div class="container col-lg-6" id="message">
        {% if messages %}
        {% for message in messages %}
        <div class="mt-2 alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>

    {% block content %}

    {% endblock content %}

    <div class="mt-auto">
      <footer class="absolute bottom-0 bg-light py-5 mt-5 border border-top py-4">
        <div class="container d-flex justify-content-center">
          <p>
            <span>Copyright &copy; 2023 </span>
            <span class="mx-2">.</span>
            <a class="nav-link d-inline" href="https://github.com/balewgize/background-remover" target="_blank"><i
                class="fa-brands fa-github me-2"></i>Github</a>
          </p>
        </div>
      </footer>
    </div>

  </div> <!-- /container -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>

  {% block page_js %} {% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container py-5 col-lg-6 mx-auto">
  <form method="post" class="d-block" id="uploadForm" onsubmit="onSubmit()" enctype="multipart/form-data">
    <h5 class="mb-4">Drop an image below or browse files.</h5>
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary mt-3"><i class="fa-solid fa-cloud-arrow-up me-2"></i>Upload
      Image</button>
  </form>

  <div class="d-none" id="progress">
    <h5 class="me-5">Processing image...</h5>
    <p class="small">Your image is being uploaded to the server and processed.</sp>
    <div class="d-flex justify-content-center mt-5">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Processing image...</span>
      </div>
    </div>
  </div>
</div>

{% block page_js %}
<script>
  function onSubmit() {
    let uploadForm = document.querySelector("#uploadForm");
    let progress = document.querySelector("#progress");

    uploadForm.setAttribute("class", "d-none");
    progress.setAttribute("class", "d-block");

    uploadForm.submit();
  }
</script>
{% endblock %}

{% endblock %}

templates/result.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_css %}
<style>
  img {
    width: 100%;
  }
</style>

{% endblock %}

{% block content %}

<div class="container py-5 mx-auto">
  {% if user_activity.result.url %}
  <h5>Process completed.</h5>
  <p>You can download the image with transparent background (right).</p>
  <div class="mt-5 d-flex flex-column flex-lg-row">
    <div class="col-lg-5 border border-5 rounded">
      <img src="{{user_activity.image.url}}" alt="">
    </div>
    <div class="col-lg-1 my-3 my-lg-0 d-flex align-items-center justify-content-center">
      <span class="d-none d-lg-inline"><i class="fa-solid fa-angles-right"></i></span>
      <span class="d-inline d-lg-none"><i class="fa-solid fa-angles-down"></i></span>
    </div>
    <div class="col-lg-5 border border-5 rounded">
      <img src="{{user_activity.result.url}}" alt="">
    </div>
  </div>
  <div class="mt-0 mt-lg-5 d-flex justify-content-center">
    <a href="{{ user_activity.result.url }}" class="btn btn-primary my-5" download><i
        class="fa-solid fa-cloud-arrow-down me-2"></i>Download Result</a>
  </div>
  {% else %}
  <div class="">
    <h5>Process failed.</h5>
    <p>We are sorry for the inconvenience. Please try again.</p>
    <a href="{% url 'bgremove:home' %}">Upload image</a>
  </div>
  {% endif %}
</div>
{% endblock %}